spring:
  application:
    name: discount-monitoring
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/liza}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:root}
    hikari:
      maximum-pool-size: ${MAXIMUM_POOL_SIZE:20}
      jdbc-url: ${spring.datasource.url}
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
logging:
  level:
    com.hometech: ${LOG_LEVEL:trace}
  register-shutdown-hook: true
app:
  bot:
    name: ${BOT_NAME:not-valid}
    token: ${BOT_TOKEN:not-valid}
  threads-count: ${THREADS_COUNT:1}
