version: '3'
services:
  discount-app:
    image: discount-monitoring-robot:0.0.1
    container_name: discount-app
    depends_on: [ postgresql ]
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - JDBC_URL=jdbc:postgresql://postgresql:5432/discount_monitoring
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=${POSTGRES_PASSWORD}
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
  postgresql:
    image: postgres:11
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "0.0.0.0:5432:5432"
    command: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=discount_monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
